### PR TITLE
add missing return statement to out-of-order message processing

### PR DESCRIPTION
**Pull request by mvayngrib**

### CODE REVIEW

**Comment by alax** [comment]
Is there a specific reason you felt this return statement was necessary? It looks to me like it's irrelevant, but you might have seen some behavior I haven't. Thanks!

**Comment by mvayngrib** [comment]
otherwise it would continue to https://github.com/alax/forward-secrecy/blob/d7d71c596b0f40f47842e8c5614c9f4c6deeb464/src/index.js#L548 no?

**Comment by alax** [comment]
It seems you are correct. Thanks for the contribution!

**Comment by mvayngrib** [comment]
any plan on getting this audited? The source is readable and well-documented, has tests, but as you said, unaudited. Also, curious, was this the spec you used?: https://github.com/trevp/double_ratchet/wiki

**Comment by alax** [comment]
I would definitely like to get it audited, but it was just a side project and I haven't had much serious time to devote to it.

And yes, that was the spec I used.

**Comment by mvayngrib** [comment]
i'm not sure who to ask, so i'm asking you :) i'm trying to understand whether axolotl minus prekeys can be used as a drop-in replacement for OTR. The prekeys seem to imply the existence of a server, while OTR can be purely p2p

**Comment by alax** [comment]
From what I understand, OTR has to have a method for initially communicating keys, you'd just have to have your implementation communicate it's pre-keys the same way, and then update them periodically. You also would not be able to start messaging a user until you had received their pre-keys, which is why a server (where they're always available) is usually the method of choice.

**Comment by mvayngrib** [comment]
yea, in OTR you just need to communicate the identity keys, once. I guess with prekeys, after the first session initialization, you can check that before you exhaust the other person's prekeys, you send them new ones (not via a server, but in an axolotl-encrypted message). Then you can obviate the need for a server, except for maybe the first step.

**Pull request merged**
